const HERO=window.AURION_HERO||"";
(function(){const img=document.getElementById("heroImg");if(!img)return;if(HERO)img.src=HERO;else img.remove();})();
const TOOLS={
  video:{accept:"video/*,.mp4,.mov,.m4v,.webm,video/quicktime",formats:["mp4","webm","gif","mp3"]},
  audio:{accept:"audio/*,.mp3,.wav,.m4a,.aac,.caf",formats:["mp3","wav","m4a"]},
  image:{accept:"image/*,.jpg,.jpeg,.png,.webp,.heic,.heif",formats:["jpg","png","webp"]}
};
let tool="video",file=null,zipList=[],fmt="mp4",ffmpeg,ready=false,rot=0,batch=[];
const $=id=>document.getElementById(id);
function setStatus(m,cls){$("status").className="status "+(cls||"");$("status").textContent=m||"";}
function bytes(n){if(n<1024)return n+" B";if(n<1048576)return (n/1024).toFixed(1)+" KB";return (n/1048576).toFixed(2)+" MB";}
function outName(s,e){return s.replace(/\.[^.]+$/,"")+"-AURION."+e;}
function dl(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),4000);}
function speak(){try{const u=new SpeechSynthesisUtterance("Listo");u.lang="es-MX";speechSynthesis.speak(u);}catch(e){}}
function showBar(p){const b=$("bar"),i=$("barI");if(p==null){b.style.display="none";return;}b.style.display="block";i.style.width=Math.max(2,Math.min(100,p*100))+"%";}
function renderFormats(){const list=TOOLS[tool]?.formats||[];$("formats").innerHTML="";fmt=list[0]||"";list.forEach((f,i)=>{const b=document.createElement("button");b.className="chip"+(i?"":" on");b.textContent=f.toUpperCase();b.onclick=()=>{fmt=f;[...$("formats").children].forEach(c=>c.classList.remove("on"));b.classList.add("on");};$("formats").appendChild(b);});}
function setTool(next){tool=next;document.querySelectorAll(".card").forEach(c=>c.classList.toggle("active",c.dataset.tool===next));document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("on",b.dataset.go===next));$("pm").classList.toggle("hidden",next==="file"||next==="vault");$("pf").classList.toggle("hidden",next!=="file");$("pv").classList.toggle("hidden",next!=="vault");$("imageOpts").classList.toggle("hidden",next!=="image");$("mediaOpts").classList.toggle("hidden",next!=="video");$("trimWrap").classList.toggle("hidden",next!=="video"&&next!=="audio");$("audioBtn").classList.toggle("hidden",next!=="video");$("pdfBtn").classList.toggle("hidden",next!=="image");$("frameBtn").classList.toggle("hidden",next!=="video");const inp=$("file");if(TOOLS[next]){inp.accept=TOOLS[next].accept;inp.multiple=next==="image";}else{inp.accept="*/*";inp.multiple=false;}if(next!=="file"&&next!=="vault")renderFormats();if(next==="vault")renderVault();}
document.querySelectorAll(".card").forEach(c=>c.onclick=()=>setTool(c.dataset.tool));
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>setTool(b.dataset.go));
$("quality").oninput=()=>$("qval").textContent=$("quality").value;
function takeFiles(files){if(!files||!files.length){setStatus("No llegó ningún archivo.","warn");return;}batch=[...files];file=files[0];$("fname").textContent=files.map(f=>f.name).join(", ");$("fmeta").textContent=files.map(f=>bytes(f.size)+" · "+(f.type||"archivo")).join(" | ");$("convertBtn").disabled=false;const p=$("prev");try{if(file.type.startsWith("image/")){p.src=URL.createObjectURL(file);p.style.display="block";}else p.style.display="none";}catch(e){p.style.display="none";}if(file.size>45*1024*1024&&(tool==="video"||tool==="audio"))setStatus("Listo para convertir. Archivo grande ("+bytes(file.size)+"). En iPhone usa 720p o recorta.","warn");else setStatus("Archivo cargado. Ya puedes convertir o sellar origen.","ok");}
function bindPick(picker,fn){picker.addEventListener("change",()=>{if(picker.files&&picker.files.length)fn([...picker.files]);picker.value="";});}
function bindDrop(zone,picker,fn){bindPick(picker,fn);zone.addEventListener("dragover",e=>{e.preventDefault();zone.classList.add("over");});zone.addEventListener("dragleave",()=>zone.classList.remove("over"));zone.addEventListener("drop",e=>{e.preventDefault();zone.classList.remove("over");if(e.dataTransfer.files.length)fn([...e.dataTransfer.files]);});}
bindDrop($("drop"),$("file"),takeFiles);
bindDrop($("dropZip"),$("zipFiles"),files=>{zipList=files;$("znames").textContent=files.map(f=>f.name).join(", ");});
bindDrop($("dropVault"),$("vaultFiles"),files=>addVaultFiles(files));
document.addEventListener("paste",e=>{const items=[...((e.clipboardData&&e.clipboardData.files)||[])];if(items.length&&(tool==="image"||tool==="video"||tool==="audio"))takeFiles(items);});
$("rotL").onclick=()=>{rot=(rot+270)%360;setStatus("Rotacion "+rot+"°");};
$("rotR").onclick=()=>{rot=(rot+90)%360;setStatus("Rotacion "+rot+"°");};
async function raster(f,ext,q){const bmp=await createImageBitmap(f);let tw=bmp.width,th=bmp.height;const fit=$("fit").value;if(fit==="1080"){tw=1080;th=Math.round(bmp.height*1080/bmp.width);}if(fit==="square"){tw=th=1080;}if(fit==="tiktok"){tw=1080;th=1920;}if(fit==="story"){tw=1080;th=1350;}const c=document.createElement("canvas");if(rot===90||rot===270){c.width=th;c.height=tw;}else{c.width=tw;c.height=th;}const ctx=c.getContext("2d");ctx.fillStyle="#000";ctx.fillRect(0,0,c.width,c.height);ctx.save();if(rot){ctx.translate(c.width/2,c.height/2);ctx.rotate(rot*Math.PI/180);ctx.translate(-tw/2,-th/2);}const sc=Math.max(tw/bmp.width,th/bmp.height);ctx.drawImage(bmp,(tw-bmp.width*sc)/2,(th-bmp.height*sc)/2,bmp.width*sc,bmp.height*sc);ctx.restore();const mime=ext==="jpg"?"image/jpeg":ext==="webp"?"image/webp":"image/png";return new Promise(r=>c.toBlob(r,mime,q/100));}
async function loadFF(){if(ready)return;if(typeof FFmpegWASM==="undefined"||typeof FFmpegUtil==="undefined")throw new Error("No cargó el motor (red / unpkg). Recarga con WiFi.");setStatus("Cargando motor de video (una vez)…");const {FFmpeg}=FFmpegWASM;const {toBlobURL}=FFmpegUtil;ffmpeg=new FFmpeg();ffmpeg.on("progress",({progress})=>showBar(progress||0));const base="https://unpkg.com/@ffmpeg/core@0.12.6/dist/umd";await ffmpeg.load({coreURL:await toBlobURL(base+"/ffmpeg-core.js","text/javascript"),wasmURL:await toBlobURL(base+"/ffmpeg-core.wasm","application/wasm")});ready=true;}
async function convertMedia(f,ext,opt={}){await loadFF();const {fetchFile}=FFmpegUtil;const inn="in.bin",outExt=opt.forceAudio?"mp3":ext,out="out."+outExt;await ffmpeg.writeFile(inn,await fetchFile(f));const q=+$("quality").value;const crf=String(Math.round(36-(q-40)*16/60));const trim=[];if($("tStart").value)trim.push("-ss",$("tStart").value);if($("tEnd").value)trim.push("-to",$("tEnd").value);let mid;if(opt.frame){mid=["-frames:v","1","-q:v","3"];}else if(opt.forceAudio||outExt==="mp3"){mid=["-vn","-acodec","libmp3lame","-q:a",String(Math.round((100-q)/20))];}else if(outExt==="wav"){mid=["-vn"];}else if(outExt==="m4a"){mid=["-vn","-c:a","aac"];}else if(outExt==="gif"){mid=["-vf","fps=12,scale=480:-1:flags=lanczos"];}else if(outExt==="webm"){mid=["-c:v","libvpx","-b:v","1M","-c:a","libvorbis"];}else{const vf=[];const sc=$("vscale").value;if(sc==="720")vf.push("scale=-2:720");if(sc==="1080")vf.push("scale=-2:1080");mid=["-c:v","libx264","-preset","ultrafast","-crf",crf,"-pix_fmt","yuv420p","-movflags","+faststart"];if(vf.length)mid.push("-vf",vf.join(","));if($("mute").checked)mid.push("-an");else mid.push("-c:a","aac","-b:a","128k");}await ffmpeg.exec(["-i",inn,...trim,...mid,"-y",out]);const data=await ffmpeg.readFile(out);try{await ffmpeg.deleteFile(inn);await ffmpeg.deleteFile(out);}catch(e){}return {blob:new Blob([data.buffer]),name:outName(f.name,opt.frame?"jpg":outExt)};}
async function run(forceAudio){if(!file){setStatus("Elige un archivo primero. Toca el recuadro punteado.","warn");return;}$("convertBtn").disabled=true;showBar(0.05);try{if(tool==="image"){const list=batch.length?batch:[file];if(list.length>1){const blobs=[];for(let i=0;i<list.length;i++){setStatus("Imagen "+(i+1)+" / "+list.length);showBar((i+1)/list.length);blobs.push({name:outName(list[i].name,fmt),blob:await raster(list[i],fmt,+$("quality").value)});}dl(await filesToZip(blobs.map(b=>new File([b.blob],b.name))),"AURION-lote.zip");setStatus("Lote listo: "+list.length+" imagenes.","ok");}else{const blob=await raster(file,fmt,+$("quality").value);dl(blob,outName(file.name,fmt));setStatus("Listo.","ok");}speak();}else{const r=await convertMedia(file,fmt,{forceAudio});dl(r.blob,r.name);setStatus("Listo: "+r.name+" · "+bytes(r.blob.size),"ok");speak();}}catch(e){setStatus("Fallo: "+(e.message||e)+". Prueba WiFi, archivo más liviano o 720p.","warn");}finally{$("convertBtn").disabled=false;showBar(null);}}
$("convertBtn").onclick=()=>run(false);
$("audioBtn").onclick=()=>run(true);
$("frameBtn").onclick=async()=>{if(!file)return;try{showBar(0.2);const r=await convertMedia(file,"jpg",{frame:true});dl(r.blob,r.name);setStatus("Frame extraido.","ok");}catch(e){setStatus("No se pudo sacar el frame.","warn");}showBar(null);};
$("pdfBtn").onclick=async()=>{const list=batch.length?batch:(file?[file]:[]);if(!list.length)return;const pages=[];for(const f of list){const blob=await raster(f,"jpg",+$("quality").value);const jpeg=new Uint8Array(await blob.arrayBuffer());const bmp=await createImageBitmap(blob);pages.push({jpeg,w:bmp.width,h:bmp.height});}const enc=new TextEncoder();const parts=[];const starts=[];const add=s=>parts.push(typeof s==="string"?enc.encode(s):s);const mark=()=>starts.push(parts.reduce((n,p)=>n+p.length,0));add("%PDF-1.4\n");mark();add("1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n");mark();let kids="";for(let i=0;i<pages.length;i++)kids+=(3+i*3)+" 0 R ";add("2 0 obj<< /Type /Pages /Count "+pages.length+" /Kids ["+kids+"] >>endobj\n");pages.forEach((p,i)=>{const po=3+i*3,co=po+1,io=po+2;mark();add(po+" 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 "+p.w+" "+p.h+"] /Contents "+co+" 0 R /Resources << /XObject << /Im"+i+" "+io+" 0 R >> >> >>endobj\n");const st="q "+p.w+" 0 0 "+p.h+" 0 0 cm /Im"+i+" Do Q";mark();add(co+" 0 obj<< /Length "+st.length+" >>stream\n"+st+"\nendstream\nendobj\n");mark();add(io+" 0 obj<< /Type /XObject /Subtype /Image /Width "+p.w+" /Height "+p.h+" /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length "+p.jpeg.length+" >>stream\n");add(p.jpeg);add("\nendstream\nendobj\n");});const xrefAt=parts.reduce((n,p)=>n+p.length,0);let xref="xref\n0 "+(starts.length+1)+"\n0000000000 65535 f \n";starts.forEach(o=>xref+=String(o).padStart(10,"0")+" 00000 n \n");add(xref);add("trailer<< /Size "+(starts.length+1)+" /Root 1 0 R >>\nstartxref\n"+xrefAt+"\n%%EOF");dl(new Blob(parts,{type:"application/pdf"}),"AURION-imagenes.pdf");setStatus("PDF listo.","ok");speak();};
$("dlUrlBtn").onclick=async()=>{const url=$("url").value.trim();if(!url)return;try{const blob=await(await fetch(url)).blob();dl(blob,url.split("/").pop()||"archivo");$("zstatus").textContent="Descargado.";}catch{$("zstatus").textContent="CORS bloqueó el link. Descárgalo en otra pestaña y súbelo aquí.";}};
function crc32(buf){if(!window.__crc){const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;t[n]=c;}window.__crc=t;}let c=~0;for(let i=0;i<buf.length;i++)c=window.__crc[(c^buf[i])&255]^(c>>>8);return~c>>>0;}
function u16(n){const b=new Uint8Array(2);new DataView(b.buffer).setUint16(0,n,true);return b;}
function u32(n){const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,n,true);return b;}
async function filesToZip(files){const enc=new TextEncoder();const chunks=[],central=[];let offset=0;for(const f of files){const data=new Uint8Array(await f.arrayBuffer());const name=enc.encode((f.name||"archivo").replace(/^.*[\\\/]/,""));const crc=crc32(data);const local=[u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data];chunks.push(...local);central.push(u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name);offset+=30+name.length+data.length;}const centralSize=central.reduce((s,x)=>s+x.length,0);return new Blob([...chunks,...central,u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(centralSize),u32(offset),u16(0)],{type:"application/zip"});}
$("zipBtn").onclick=async()=>{if(!zipList.length){$("zstatus").textContent="Elige archivos primero.";return;}dl(await filesToZip(zipList),"AURION-paquete.zip");$("zstatus").textContent="ZIP listo.";speak();};
$("gzBtn").onclick=async()=>{const srcs=zipList.length?zipList:(file?[file]:[]);if(!srcs.length){$("zstatus").textContent="Elige archivos.";return;}if(!window.CompressionStream){$("zstatus").textContent="Este navegador no soporta GZIP.";return;}if(srcs.length===1){const blob=await new Response(srcs[0].stream().pipeThrough(new CompressionStream("gzip"))).blob();dl(blob,srcs[0].name+".gz");}else{const out=[];for(const s of srcs){const blob=await new Response(s.stream().pipeThrough(new CompressionStream("gzip"))).blob();out.push(new File([blob],s.name+".gz"));}dl(await filesToZip(out),"AURION-gzip.zip");}$("zstatus").textContent="GZIP listo.";};
const DB_NAME="aurion-vault",STORE="files";
function idb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"id"});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function vaultAll(){const db=await idb();return new Promise((res,rej)=>{const q=db.transaction(STORE,"readonly").objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error);});}
async function vaultPut(rec){const db=await idb();return new Promise((res,rej)=>{const q=db.transaction(STORE,"readwrite").objectStore(STORE).put(rec);q.onsuccess=()=>res();q.onerror=()=>rej(q.error);});}
async function vaultDel(id){const db=await idb();return new Promise((res,rej)=>{const q=db.transaction(STORE,"readwrite").objectStore(STORE).delete(id);q.onsuccess=()=>res();q.onerror=()=>rej(q.error);});}
$("note").value=localStorage.getItem("aurion-note")||"";
$("noteBtn").onclick=()=>{localStorage.setItem("aurion-note",$("note").value);$("vstatus").textContent="Nota guardada en este dispositivo.";};
async function addVaultFiles(files){for(const f of files){await vaultPut({id:Date.now()+"-"+Math.random().toString(36).slice(2),name:f.name,type:f.type,size:f.size,blob:f,at:Date.now()});}$("vstatus").textContent="Guardado en vault: "+files.length;renderVault();}
$("vaultAddBtn").onclick=async()=>{if(!file){setStatus("Elige un archivo primero.","warn");return;}await addVaultFiles(batch.length?batch:[file]);setStatus("Copiado al Vault MENTAL STATE.","ok");};
async function renderVault(){const box=$("vlist");box.innerHTML="";const rows=await vaultAll();if(!rows.length){box.innerHTML="<p class='hint'>Vacio.</p>";return;}rows.sort((a,b)=>b.at-a.at).forEach(r=>{const d=document.createElement("div");d.className="item";d.innerHTML="<div><b></b><small></small></div><div class='row' style='flex:0'><button data-dl>Bajar</button><button data-rm>X</button></div>";d.querySelector("b").textContent=r.name;d.querySelector("small").textContent=bytes(r.size)+" · "+new Date(r.at).toLocaleString();d.querySelector("[data-dl]").onclick=()=>dl(r.blob,r.name);d.querySelector("[data-rm]").onclick=async()=>{await vaultDel(r.id);renderVault();};box.appendChild(d);});}
setTool("video");
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
